<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit73f898b2e10bc1d555f40ab5e4996e1f
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit73f898b2e10bc1d555f40ab5e4996e1f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit73f898b2e10bc1d555f40ab5e4996e1f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit73f898b2e10bc1d555f40ab5e4996e1f::$classMap;

        }, null, ClassLoader::class);
    }
}
